### PR TITLE
Please get new code

### PR DESCRIPTION
**Pull request by vadimrm**

### CODE REVIEW

**Comment by jdkoftinoff** [comment]
Thank you very much for these important updated, Vadim!

**Comment by vadimrm** [comment]
But you do not get my last commit!
See it on https://github.com/vadimrm/jdksmidi/commits/master
"Oct 28, 2011 Add SoloMelodyConverter() utility and some other code"

**Comment by jdkoftinoff** [comment]
pulled and merged now

**Comment by vadimrm** [comment]
ok, thanks :)

**Pull request closed without merging**
